apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-group2-deployment
  labels:
    app: group2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group2
  template:
    metadata:
      labels:
        app: group2
    spec:
      serviceAccountName: clo835-group2
      containers:
      - name: webapp-group2-deployment
        image: 209090547293.dkr.ecr.us-east-1.amazonaws.com/finalproject:appimage
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          value: 192.168.52.128
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
        - name: BUCKETNAME
          valueFrom:
            configMapKeyRef:
              name: group2-app-config
              key: bucket
        - name: BGIMG
          valueFrom:
            configMapKeyRef:
              name: group2-app-config
              key: background-img
                  
        - name: GRPNAME
          valueFrom:
            configMapKeyRef:
              name: group2-app-config
              key: groupname
        
        command: ["python3", "app.py"]