apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-binding
  namespace: final
subjects:
  - kind: ServiceAccount
    name: clo835-group2
    namespace: final
    apiGroup: ""
roleRef:
  kind: Role
  name: CLO835-final-group2
  apiGroup: rbac.authorization.k8s.io